import { readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import {
  parseSqlFormatterOptions,
  SqlFormatter,
  SqlFormatterOptionsValidationError,
  SqlParser,
  type SqlFormatterOptions,
} from 'rawsql-ts';
import { McpInputError } from './inputError';
import { normalizeWorkspaceRoot, resolveWorkspacePath } from './workspacePaths';

const MAX_FORMAT_CONFIG_BYTES = 1024 * 1024;

/** Formatter configuration supplied by a future SQL-generating MCP tool. */
export interface SqlFormatInput {
  configPath?: string;
  options?: Partial<SqlFormatterOptions>;
}

/** Validated formatter options and whether formatting was requested. */
export interface ResolvedSqlFormatting {
  enabled: boolean;
  options: Readonly<SqlFormatterOptions>;
}

/** Explicit wrapper for SQL generated by a tool rather than copied from evidence. */
export interface GeneratedSqlArtifact<Kind extends string = string> {
  artifactKind: Kind;
  sql: string;
}

/** Resolve formatter defaults < JSON config < inline options. */
export function resolveSqlFormatting(
  workspaceRoot: string,
  format?: SqlFormatInput,
): ResolvedSqlFormatting {
  const root = normalizeWorkspaceRoot(workspaceRoot);
  if (format === undefined) return { enabled: false, options: {} };
  if (!isPlainRecord(format)) {
    throw new McpInputError('FORMAT_INPUT_INVALID', 'format must be an object.');
  }
  const inputKeys = Object.keys(format);
  const unknownInputKey = inputKeys.find((key) => key !== 'configPath' && key !== 'options');
  if (unknownInputKey) {
    throw new McpInputError('FORMAT_INPUT_INVALID', `Unknown format field: ${unknownInputKey}`);
  }
  if (format.configPath !== undefined && typeof format.configPath !== 'string') {
    throw new McpInputError('FORMAT_INPUT_INVALID', 'format.configPath must be a string.');
  }

  const configOptions = format.configPath === undefined
    ? {}
    : readFormatterConfig(root, format.configPath);
  const inlineOptions = parseFormatterOptions(format.options ?? {}, 'format.options');
  const options = parseFormatterOptions({ ...configOptions, ...inlineOptions }, 'resolved formatter options');
  return { enabled: true, options };
}

/** Create the only artifact shape accepted by the common formatting operation. */
export function generatedSqlArtifact<Kind extends string>(artifactKind: Kind, sql: string): GeneratedSqlArtifact<Kind> {
  return { artifactKind, sql };
}

/**
 * Format one explicit generated SQL artifact. This function never walks result
 * objects, so original SQL, expressionSql, snippets, and other evidence text
 * cannot be rewritten implicitly.
 *
 * API output shape review: the explicit artifact wrapper distinguishes generated
 * SQL from evidence and preserves all artifact metadata while replacing only sql.
 */
export function formatGeneratedSqlArtifact<Artifact extends GeneratedSqlArtifact>(
  artifact: Artifact,
  formatting: ResolvedSqlFormatting,
): Artifact {
  if (!isPlainRecord(artifact) || typeof artifact.artifactKind !== 'string' || typeof artifact.sql !== 'string') {
    throw new McpInputError('GENERATED_SQL_ARTIFACT_INVALID', 'Only an explicit generated SQL artifact can be formatted.');
  }
  if (!formatting.enabled) return artifact;
  try {
    const statement = SqlParser.parse(artifact.sql);
    const sql = new SqlFormatter(formatting.options).format(statement).formattedSql;
    return { ...artifact, sql };
  } catch (error) {
    throw new McpInputError('GENERATED_SQL_FORMAT_FAILED', error instanceof Error ? error.message : String(error));
  }
}

function readFormatterConfig(workspaceRoot: string, configPath: string): SqlFormatterOptions {
  if (path.extname(configPath).toLowerCase() !== '.json') {
    throw new McpInputError('FORMAT_CONFIG_EXTENSION', 'Formatter configPath must identify a JSON file.');
  }
  const resolved = resolveWorkspacePath(workspaceRoot, configPath, 'file');
  if (statSync(resolved.absolutePath).size > MAX_FORMAT_CONFIG_BYTES) {
    throw new McpInputError('FORMAT_CONFIG_SIZE_LIMIT', `Formatter config exceeds ${MAX_FORMAT_CONFIG_BYTES} bytes.`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(resolved.absolutePath, 'utf8'));
  } catch (error) {
    throw new McpInputError('FORMAT_CONFIG_INVALID_JSON', `Formatter config is not valid JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
  return parseFormatterOptions(parsed, `formatter config ${resolved.relativePath}`);
}

function parseFormatterOptions(value: unknown, source: string): SqlFormatterOptions {
  try {
    return parseSqlFormatterOptions(value);
  } catch (error) {
    if (error instanceof SqlFormatterOptionsValidationError) {
      const code = error.code === 'SQL_FORMATTER_OPTION_UNKNOWN'
        ? 'FORMAT_OPTION_UNKNOWN'
        : 'FORMAT_OPTIONS_INVALID';
      throw new McpInputError(code, `${source}: ${error.message}`);
    }
    throw error;
  }
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null);
}
