import { readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import {
  SqlFormatter,
  SqlParser,
  VALID_PRESETS,
  type SqlFormatterOptions,
} from 'rawsql-ts';
import { McpInputError } from './inputError';
import { normalizeWorkspaceRoot, resolveWorkspacePath } from './workspacePaths';

const MAX_FORMAT_CONFIG_BYTES = 1024 * 1024;

/** Formatter configuration supplied by a future SQL-generating MCP tool. */
export interface SqlFormatInput {
  configPath?: string;
  options?: Partial<SqlFormatterOptions>;
}

/** Validated formatter options and whether formatting was requested. */
export interface ResolvedSqlFormatting {
  enabled: boolean;
  options: Readonly<SqlFormatterOptions>;
}

/** Explicit wrapper for SQL generated by a tool rather than copied from evidence. */
export interface GeneratedSqlArtifact<Kind extends string = string> {
  artifactKind: Kind;
  sql: string;
}

type FormatterOptionValidators = {
  [Key in keyof Required<SqlFormatterOptions>]: (value: unknown) => boolean;
};

const formatterOptionValidators = {
  andBreak: oneOf('none', 'before', 'after'),
  betweenOneLine: isBoolean,
  caseOneLine: isBoolean,
  castStyle: oneOf('postgres', 'standard'),
  columnAliasStyle: oneOf('explicit', 'omit', 'as', 'implicit'),
  commaBreak: oneOf('none', 'before', 'after'),
  commentStyle: oneOf('block', 'smart'),
  constraintStyle: oneOf('postgres', 'mysql'),
  cteCommaBreak: oneOf('none', 'before', 'after'),
  exportComment: (value) => isBoolean(value) || oneOf('none', 'full', 'header-only', 'top-header-only')(value),
  identifierEscape: isIdentifierEscape,
  identifierEscapeTarget: oneOf('all', 'minimal'),
  inOneLine: isBoolean,
  indentChar: isString,
  indentNestedParentheses: isBoolean,
  indentSize: isNonNegativeInteger,
  insertColumnsOneLine: isBoolean,
  joinConditionContinuationIndent: isBoolean,
  joinConditionOrderByDeclaration: isBoolean,
  joinOnBreak: oneOf('none', 'before', 'after'),
  joinOneLine: isBoolean,
  keywordCase: oneOf('none', 'upper', 'lower', 'preserve'),
  newline: oneOf('lf', 'crlf', 'cr', 'space', '\n', '\r\n', '\r', ' '),
  oneLineMaxLength: (value) => value === null || isNonNegativeInteger(value),
  orBreak: oneOf('none', 'before', 'after'),
  orderByDefaultDirectionStyle: oneOf('omit', 'explicit'),
  parameterStyle: oneOf('anonymous', 'indexed', 'named', 'original'),
  parameterSymbol: (value) => isString(value) || isDelimiterPair(value),
  parenthesesOneLine: isBoolean,
  preset: (value) => isString(value) && (VALID_PRESETS as readonly string[]).includes(value),
  sourceAliasStyle: oneOf('explicit', 'omit', 'as', 'implicit'),
  subqueryOneLine: isBoolean,
  valuesCommaBreak: oneOf('none', 'before', 'after'),
  valuesOneLine: isBoolean,
  whenOneLine: isBoolean,
  withClauseStyle: oneOf('standard', 'cte-oneline', 'full-oneline'),
} satisfies FormatterOptionValidators;

/** Resolve formatter defaults < JSON config < inline options. */
export function resolveSqlFormatting(
  workspaceRoot: string,
  format?: SqlFormatInput,
): ResolvedSqlFormatting {
  const root = normalizeWorkspaceRoot(workspaceRoot);
  if (format === undefined) return { enabled: false, options: {} };
  if (!isPlainRecord(format)) {
    throw new McpInputError('FORMAT_INPUT_INVALID', 'format must be an object.');
  }
  const inputKeys = Object.keys(format);
  const unknownInputKey = inputKeys.find((key) => key !== 'configPath' && key !== 'options');
  if (unknownInputKey) {
    throw new McpInputError('FORMAT_INPUT_INVALID', `Unknown format field: ${unknownInputKey}`);
  }
  if (format.configPath !== undefined && typeof format.configPath !== 'string') {
    throw new McpInputError('FORMAT_INPUT_INVALID', 'format.configPath must be a string.');
  }

  const configOptions = format.configPath === undefined
    ? {}
    : readFormatterConfig(root, format.configPath);
  const inlineOptions = validateFormatterOptions(format.options ?? {}, 'format.options');
  const options = validateFormatterOptions({ ...configOptions, ...inlineOptions }, 'resolved formatter options');

  // Let rawsql-ts perform its own formatter construction checks as the final authority.
  try {
    new SqlFormatter(options);
  } catch (error) {
    throw new McpInputError('FORMAT_OPTIONS_INVALID', error instanceof Error ? error.message : String(error));
  }
  return { enabled: true, options };
}

/** Create the only artifact shape accepted by the common formatting operation. */
export function generatedSqlArtifact<Kind extends string>(artifactKind: Kind, sql: string): GeneratedSqlArtifact<Kind> {
  return { artifactKind, sql };
}

/**
 * Format one explicit generated SQL artifact. This function never walks result
 * objects, so original SQL, expressionSql, snippets, and other evidence text
 * cannot be rewritten implicitly.
 *
 * API output shape review: the explicit artifact wrapper distinguishes generated
 * SQL from evidence and preserves all artifact metadata while replacing only sql.
 */
export function formatGeneratedSqlArtifact<Artifact extends GeneratedSqlArtifact>(
  artifact: Artifact,
  formatting: ResolvedSqlFormatting,
): Artifact {
  if (!isPlainRecord(artifact) || typeof artifact.artifactKind !== 'string' || typeof artifact.sql !== 'string') {
    throw new McpInputError('GENERATED_SQL_ARTIFACT_INVALID', 'Only an explicit generated SQL artifact can be formatted.');
  }
  if (!formatting.enabled) return artifact;
  try {
    const statement = SqlParser.parse(artifact.sql);
    const sql = new SqlFormatter(formatting.options).format(statement).formattedSql;
    return { ...artifact, sql };
  } catch (error) {
    throw new McpInputError('GENERATED_SQL_FORMAT_FAILED', error instanceof Error ? error.message : String(error));
  }
}

function readFormatterConfig(workspaceRoot: string, configPath: string): SqlFormatterOptions {
  if (path.extname(configPath).toLowerCase() !== '.json') {
    throw new McpInputError('FORMAT_CONFIG_EXTENSION', 'Formatter configPath must identify a JSON file.');
  }
  const resolved = resolveWorkspacePath(workspaceRoot, configPath, 'file');
  if (statSync(resolved.absolutePath).size > MAX_FORMAT_CONFIG_BYTES) {
    throw new McpInputError('FORMAT_CONFIG_SIZE_LIMIT', `Formatter config exceeds ${MAX_FORMAT_CONFIG_BYTES} bytes.`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(resolved.absolutePath, 'utf8'));
  } catch (error) {
    throw new McpInputError('FORMAT_CONFIG_INVALID_JSON', `Formatter config is not valid JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
  return validateFormatterOptions(parsed, `formatter config ${resolved.relativePath}`);
}

function validateFormatterOptions(value: unknown, source: string): SqlFormatterOptions {
  if (!isPlainRecord(value)) {
    throw new McpInputError('FORMAT_OPTIONS_INVALID', `${source} must be a JSON object.`);
  }
  const result: Record<string, unknown> = {};
  for (const [key, option] of Object.entries(value)) {
    const validator = formatterOptionValidators[key as keyof typeof formatterOptionValidators];
    if (!validator) {
      throw new McpInputError('FORMAT_OPTION_UNKNOWN', `Unknown formatter option in ${source}: ${key}`);
    }
    if (option === undefined) continue;
    if (!validator(option)) {
      throw new McpInputError('FORMAT_OPTIONS_INVALID', `Invalid value for formatter option ${key} in ${source}.`);
    }
    result[key] = option;
  }
  return result as SqlFormatterOptions;
}

function isIdentifierEscape(value: unknown): boolean {
  return oneOf('quote', 'backtick', 'bracket', 'none')(value) || isDelimiterPair(value);
}

function isDelimiterPair(value: unknown): boolean {
  return isPlainRecord(value)
    && Object.keys(value).sort().join(',') === 'end,start'
    && isString(value.start)
    && isString(value.end);
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null);
}

function isBoolean(value: unknown): value is boolean {
  return typeof value === 'boolean';
}

function isString(value: unknown): value is string {
  return typeof value === 'string';
}

function isNonNegativeInteger(value: unknown): value is number {
  return Number.isSafeInteger(value) && Number(value) >= 0;
}

function oneOf<const Values extends readonly string[]>(...values: Values): (value: unknown) => value is Values[number] {
  return (value: unknown): value is Values[number] => typeof value === 'string' && values.includes(value);
}
