-- EC domain: users, products, orders, and order_items for ZTD practice.
CREATE TABLE users (
  users_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  created_at timestamp NOT NULL
);

CREATE TABLE products (
  products_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL,
  category_id bigint
);

CREATE TABLE orders (
  orders_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(users_id),
  order_date date NOT NULL,
  status text NOT NULL
);

CREATE TABLE order_items (
  order_items_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES orders(orders_id),
  product_id bigint NOT NULL REFERENCES products(products_id),
  quantity int NOT NULL,
  unit_price numeric NOT NULL
);
