import path from 'node:path';

export type ModelGenFormat = 'interface' | 'row-mapping' | 'spec';

export interface ModelGenColumn {
  columnName: string;
  propertyName: string;
  tsType: string;
}

export interface RenderModelGenInput {
  command: string;
  format: ModelGenFormat;
  sqlFile: string;
  specId: string;
  interfaceName: string;
  mappingName: string;
  specName: string;
  placeholderMode: 'named' | 'positional' | 'none';
  allowPositional: boolean;
  orderedParamNames: string[];
  columns: ModelGenColumn[];
}

export function renderModelGenFile(input: RenderModelGenInput): string {
  const parts: string[] = [];
  parts.push(`// Generated by: ${input.command}`);
  parts.push('// DO NOT COMMIT without review. Adjust nullability, cardinality, normalization, and example values as needed.');
  parts.push('// Review rowMapping.key and rerun this command after SQL or schema changes.');
  if (input.allowPositional && input.placeholderMode === 'positional') {
    parts.push('// Legacy warning: this scaffold was generated from positional placeholders. Prefer rewriting the SQL asset to named parameters (:name).');
  } else {
    parts.push('// names-first reminder: SQL asset files should use named parameters (:name).');
  }
  parts.push('');

  if (input.format === 'row-mapping' || input.format === 'spec') {
    const importNames = input.format === 'spec' ? 'rowMapping, type QuerySpec' : 'rowMapping';
    parts.push(`import { ${importNames} } from '@rawsql-ts/sql-contract';`);
    parts.push('');
  }

  parts.push(renderInterface(input.interfaceName, input.columns));

  if (input.format === 'row-mapping' || input.format === 'spec') {
    parts.push('');
    parts.push(renderMapping(input.mappingName, input.interfaceName, input.columns));
  }

  if (input.format === 'spec') {
    parts.push('');
    parts.push(renderSpec(input));
  }

  return `${parts.join('\n')}\n`;
}

export function toModelPropertyName(columnName: string): string {
  const normalized = columnName
    .trim()
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((segment, index) => {
      const lower = segment.toLowerCase();
      if (index === 0) {
        return lower;
      }
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('');
  const prefixed = /^[A-Za-z_]/.test(normalized.charAt(0) ?? '') ? normalized : `_${normalized}`;
  if (!prefixed) {
    throw new Error(`Failed to derive a TypeScript property name from column "${columnName}".`);
  }
  return prefixed;
}

export function deriveModelGenNames(relativeSqlFile: string): {
  interfaceName: string;
  mappingName: string;
  specName: string;
  specId: string;
} {
  const withoutExtension = relativeSqlFile.replace(/\.[^.]+$/u, '');
  const normalizedPath = withoutExtension.replace(/\\/g, '/');
  const segments = normalizedPath.split('/').filter(Boolean);
  const lastSegment = segments[segments.length - 1] ?? 'query';
  const interfaceName = `${toPascalCase(lastSegment)}Row`;
  const baseCamel = toCamelCase(lastSegment);
  const specId =
    segments.length === 1
      ? baseCamel
      : `${segments.slice(0, -1).join('.')}.${baseCamel}`;
  return {
    interfaceName,
    mappingName: `${baseCamel}Mapping`,
    specName: `${baseCamel}Spec`,
    specId
  };
}

export function normalizeGeneratedSqlFile(relativeSqlFile: string): string {
  return relativeSqlFile.split(path.sep).join('/').replace(/\\/g, '/');
}

function renderInterface(interfaceName: string, columns: ModelGenColumn[]): string {
  const fields = columns.map((column) => `  ${column.propertyName}: ${column.tsType};`).join('\n');
  return `export interface ${interfaceName} {\n${fields}\n}`;
}

function renderMapping(mappingName: string, interfaceName: string, columns: ModelGenColumn[]): string {
  const keyName = columns[0]?.propertyName ?? 'id';
  const mapEntries = columns
    .map((column) => `    ${column.propertyName}: ${renderTsStringLiteral(column.columnName)},`)
    .join('\n');
  return `export const ${mappingName} = rowMapping<${interfaceName}>({\n  name: ${renderTsStringLiteral(interfaceName.replace(/Row$/u, ''))},\n  key: ${renderTsStringLiteral(keyName)},\n  columnMap: {\n${mapEntries}\n  },\n});`;
}

function renderSpec(input: RenderModelGenInput): string {
  const paramsType = renderParamsType(input.placeholderMode, input.orderedParamNames);
  const paramsExample = renderParamsExample(input.placeholderMode, input.orderedParamNames);
  const outputExample = input.columns
    .map((column) => `      ${column.propertyName}: ${renderExampleValue(column.tsType)},`)
    .join('\n');
  return `export const ${input.specName}: QuerySpec<${paramsType}, ${input.interfaceName}> = {\n  id: ${renderTsStringLiteral(input.specId)},\n  sqlFile: ${renderTsStringLiteral(input.sqlFile)},\n  params: { shape: ${renderTsStringLiteral(input.placeholderMode === 'none' ? 'positional' : input.placeholderMode)}, example: ${paramsExample} },\n  output: {\n    mapping: ${input.mappingName},\n    example: {\n${outputExample}\n    },\n  },\n};`;
}

function renderParamsType(mode: 'named' | 'positional' | 'none', orderedParamNames: string[]): string {
  if (mode === 'named') {
    return `{ ${orderedParamNames.map((name) => `${name}: unknown`).join('; ')} }`;
  }
  if (mode === 'positional') {
    return 'unknown[]';
  }
  return '[]';
}

function renderParamsExample(mode: 'named' | 'positional' | 'none', orderedParamNames: string[]): string {
  if (mode === 'named') {
    const properties = orderedParamNames.map((name) => `${name}: null`).join(', ');
    return `{ ${properties} }`;
  }
  if (mode === 'positional') {
    return `[${orderedParamNames.map(() => 'null').join(', ')}]`;
  }
  return '[]';
}

function renderExampleValue(tsType: string): string {
  if (tsType.endsWith('[]')) {
    return '[]';
  }
  if (tsType === 'number') {
    return '0';
  }
  if (tsType === 'string') {
    return "''";
  }
  if (tsType === 'boolean') {
    return 'false';
  }
  if (tsType === 'Uint8Array') {
    return 'new Uint8Array()';
  }
  if (tsType === 'any') {
    return 'null';
  }
  return 'null as unknown';
}

function renderTsStringLiteral(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, '\\\'')}'`;
}

function toPascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/u)
    .filter(Boolean)
    .map((segment) => {
      const lower = segment.toLowerCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('') || 'Query';
}

function toCamelCase(value: string): string {
  const pascal = toPascalCase(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}
