create table users (
  user_id bigint generated by default as identity primary key,
  email text not null unique,
  display_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default current_timestamp
);

create index idx_users_is_active
  on users (is_active, user_id);
